services:
  postgres:
    image: postgres:15
    container_name: postgres_informatics_companies
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: annual_french_informatics_companies
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagster-code:
    build:
      context: .
      dockerfile: dagster-informatics-companies/Dockerfile
    env_file:
      - .env
    container_name: dagster_code
    restart: always
    environment:
      DAGSTER_HOME: /app
      DBT_PROFILES_DIR: /dbt_informatics_companies
      DAGSTER_POSTGRES_HOST: postgres
      DAGSTER_POSTGRES_USER: postgres
      DAGSTER_POSTGRES_PASSWORD: postgres
    command: >
      uv run dagster api grpc
      -h 0.0.0.0
      -p 4000
      -m dagster_informatics_companies.definitions
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4000"]
      interval: 10s
      timeout: 5s
      retries: 5

  dagster-webserver:
    build:
      context: .
      dockerfile: dagster-informatics-companies/Dockerfile
    env_file:
      - .env
    container_name: dagster_webserver
    restart: always
    depends_on:
      dagster-code:
        condition: service_healthy
    environment:
      DAGSTER_HOME: /app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: annual_french_informatics_companies
    ports:
      - "3000:3000"
    command: >
      uv run dagster-webserver
      -h 0.0.0.0
      -p 3000
      -w workspace.yaml

  dagster-daemon:
    build:
      context: .
      dockerfile: dagster-informatics-companies/Dockerfile
    env_file:
      - .env
    container_name: dagster_daemon
    restart: always
    depends_on:
      dagster-code:
        condition: service_healthy
    environment:
      DAGSTER_HOME: /app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: annual_french_informatics_companies
    command: >
      uv run dagster-daemon run

volumes:
  postgres_data: