sources:
  - name: codes_nafs
    database: annual_french_informatics_companies  
    schema: public
    tables:
      - name: code_naf
        columns:
          - name: subclasses_codes
            tests:
              - not_null
              - unique
          
          - name: subclasses_title
            tests:
              - not_null

          - name: classe_title
            tests:
              - not_null
          
          - name: classes_codes
            tests:
              - not_null
            
          - name: section_title
            tests:
              - not_null

      - name: companies

