sources:
  - name: codes_nafs_companies
    database: annual_french_informatics_companies  
    schema: public
    tables:
      - name: code_naf
        columns:
          - name: subclasses_codes
            tests:
              - not_null
              - unique
          
          - name: subclasses_title
            tests:
              - not_null

          - name: classe_title
            tests:
              - not_null
          
          - name: classes_codes
            tests:
              - not_null
            
          - name: section_title
            tests:
              - not_null

      - name: companies

      - name: regions
        columns:
          - name: id
            tests:
              - unique
              - not_null
          
          - name: code
            tests:
              - unique
              - not_null
        
          - name: name
            tests:
              - unique
              - not_null
          
          - name: slug
            tests:
              - unique
              - not_null

      - name: departments
        columns:
          - name: id
            tests:
              - unique
              - not_null
          
          - name: code
            tests:
              - unique
              - not_null
        
          - name: name
            tests:
              - unique
              - not_null
          
          - name: slug
            tests:
              - unique
              - not_null
          
          - name: region_code
            tests:
              - not_null
